import { v } from "convex/values";
import { internalAction,internalMutation } from "../_generated/server";
import { internal } from "../_generated/api";
import { requireWorkspaceMember } from "../workspaces/Access";
import { canCompleteSource } from "@pluribus/core/sources/domain";
import { capture } from "./Model";
import { scrapePage } from "./Firecrawl";
const identity={id:v.id("sources"),revision:v.number()};
export const begin=internalMutation({args:identity,returns:v.union(v.null(),v.object({url:v.string(),prompt:v.optional(v.string())})),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row || row.revision!==args.revision || row.status!=="queued")return null;try{await requireWorkspaceMember(ctx,row.workspaceId,row.userId);}catch{await ctx.db.patch(row._id,{status:"failed",error:"Workspace access changed"});return null;}await ctx.db.patch(row._id,{status:"fetching"});return {url:row.url,prompt:row.prompt};}});
export const complete=internalMutation({args:{...identity,capture:v.optional(capture),error:v.optional(v.string())},returns:v.null(),handler:async(ctx,args)=>{const row=await ctx.db.get(args.id);if(!row || !canCompleteSource(row,args.revision))return null;if(args.capture && args.capture.content.length+(args.capture.data?.length??0)>150000)throw new Error("Capture too large");await ctx.db.patch(row._id,args.capture ? {status:"ready",capture:args.capture,error:undefined}:{status:"failed",error:args.error??"Retrieval failed"});return null;}});
export const fetch=internalAction({args:identity,returns:v.null(),handler:async(ctx,args)=>{const request=await ctx.runMutation(internal.sources.Jobs.begin,args);if(!request)return null;try{const result=await scrapePage(request);await ctx.runMutation(internal.sources.Jobs.complete,{...args,capture:{...result,id:crypto.randomUUID(),capturedAt:Date.now()}});}catch(error){await ctx.runMutation(internal.sources.Jobs.complete,{...args,error:error instanceof Error && error.message==="Firecrawl is not configured" ? error.message : "Page retrieval failed. Check the URL and provider configuration."});}return null;}});
